name: CI

on:
  pull_request:
    branches:
      - master
      - henri
  push:
    branches:
      - master
      - henri

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 19
        distribution: 'temurin'
    - name: Build
      run: ./mvnw --no-transfer-progress -B clean verify --file pom.xml -PfullBuild
